import fs from 'node:fs';
import path from 'node:path';

import yaml from 'js-yaml';

import { PACKAGE_CONFIG_FILENAME } from '../package/config';

import { cli, setupUncaughtExceptionHandler } from './cli';

setupUncaughtExceptionHandler();

/**
 * Programmatic entry point for data-package bin shims generated by `filedist init`.
 *
 * Builds a synthetic single-set config from CLI args pointing to this data package.
 * Selectors (--files, --presets, etc.) are applied from the CLI args; omitting them
 * extracts all files. The data package's own .filedist-package.yml is NOT used as
 * the CLI bootstrap config here.
 *
 * @param binDir     - The bin/ directory of the data package (__dirname from the shim).
 * @param args       - CLI arguments (without node + script, i.e. process.argv.slice(2)).
 * @param configFile - Optional bootstrap config filename to inject as --config in the
 *                     consumer's cwd. When omitted the consumer's default .filedist.yml is used.
 */

const FLAGS_WITH_VALUE = new Set([
  '--output',
  '-o',
  '--files',
  '--exclude',
  '--content-regex',
  '--presets',
  '--config',
]);

const KNOWN_COMMANDS = new Set(['install', 'check', 'list', 'remove', 'init', 'presets', 'update']);

/** Returns the first positional (non-flag, non-command) argument, or undefined. */
function findUserPositional(args: string[]): string | undefined {
  for (let i = 0; i < args.length; i++) {
    if (args[i].startsWith('-')) {
      if (FLAGS_WITH_VALUE.has(args[i])) i++; // skip the value
    } else if (i === 0 && KNOWN_COMMANDS.has(args[i])) {
      // first element is a known command word, not a package
    } else {
      return args[i];
    }
  }
  // eslint-disable-next-line no-undefined
  return undefined;
}

export async function binpkg(binDir: string, args: string[], configFile?: string): Promise<void> {
  // eslint-disable-next-line no-undefined
  if (findUserPositional(args) !== undefined) {
    // eslint-disable-next-line no-console
    console.log('Cannot pass a package argument when invoked from a data package bin shim');
    // eslint-disable-next-line unicorn/no-process-exit
    process.exit(1);
  }

  const pkgRootDir = path.join(binDir, '..');
  const pkgJson = JSON.parse(fs.readFileSync(path.join(pkgRootDir, 'package.json')).toString()) as {
    name: string;
  };
  const pkgName = pkgJson.name;

  // Read defaultPresets from .filedist-package.yml (not package.json)
  let defaultPresets: string[] = [];
  const packageConfigPath = path.join(pkgRootDir, PACKAGE_CONFIG_FILENAME);
  if (fs.existsSync(packageConfigPath)) {
    const raw = fs.readFileSync(packageConfigPath, 'utf8');
    const parsed = yaml.load(raw) as { defaultPresets?: string[] } | null;
    defaultPresets = parsed?.defaultPresets ?? [];
  }

  let effectiveArgs = [...args];

  // Determine the config flag to inject (kept separate so it can be placed after the command)
  let configFlagPair: string[] = [];
  if (configFile && !effectiveArgs.includes('--config')) {
    configFlagPair = ['--config', configFile];
  }

  if (
    !effectiveArgs.includes('--presets') &&
    !effectiveArgs.includes('--all') &&
    defaultPresets.length > 0
  ) {
    effectiveArgs.push('--presets', defaultPresets.join(','));
  }

  // Find the command word (first known command in the args, ignoring flags and their values)
  let searchArgs = effectiveArgs;
  if (searchArgs[0] === '--config') {
    searchArgs = searchArgs.slice(2); // skip any user-supplied --config <value>
  }
  const commandArg = KNOWN_COMMANDS.has(searchArgs[0]) ? searchArgs[0] : 'install';

  // Split into: flags before command | command | flags after command
  // --config is always placed AFTER the command so cli.ts can detect the command word correctly
  const commandIdx = effectiveArgs.indexOf(commandArg);
  const beforeCmd = commandIdx > 0 ? effectiveArgs.slice(0, commandIdx) : [];
  const afterCmd = commandIdx >= 0 ? effectiveArgs.slice(commandIdx + 1) : effectiveArgs;

  const exitCode = await cli(
    ['node', 'filedist', ...beforeCmd, commandArg, pkgName, ...configFlagPair, ...afterCmd],
    process.cwd(),
  );
  // eslint-disable-next-line unicorn/no-process-exit
  process.exit(exitCode);
}
